image: node:14.13.1-alpine3.12

before_script:
  - npm install @angular/cli

build:
  stage: build
  script:
    # Install dependencies
    - npm install
    # Build App
    - npm run build
    # Test App
    - npm test --watch=false
  only:
    - master

cache:
    paths:
        - node_modules/
